changing package name for Debian 11 onwards
fraenki/puppet-proftpd pull request #40
Opened 2023-01-23 08:08 UTC by jbender81

adding compat check for Debian as well to reduce backwardcompat issues

2023-01-23 10:05 UTC, fraenki requested changes

2023-01-23 10:05 UTC, fraenki commented on manifests/init.pp
> +  if (($facts['os']['name'] == 'Debian') and ($facts['os']['release']['major'] < 8 )){
I'd rather avoid those conditions.... the metadata.json file clearly states which operating system is supported, so this is kind of redundant.

2023-01-24 07:55 UTC, jbender81 commented on manifests/init.pp
> +  if (($facts['os']['name'] == 'Debian') and ($facts['os']['release']['major'] < 8 )){
Done as requested

2023-02-21 09:33 UTC, fraenki approved these changes

2023-02-21 09:34 UTC, merged

2023-02-21 09:34 UTC, fraenki commented
Merged, thanks!